import type { CandidateSignal } from './domain';

export const demoSignals: CandidateSignal[] = [
  { id:'ai-agents-br', topic:'Agentes de IA entrando no trabalho real', angle:'O que já mudou fora do Brasil e o que tende a chegar ao mercado brasileiro antes da saturação local.', category:'tecnologia', regime:'PRE_TREND', demand:52, demandVelocity:18, demandAcceleration:16, supply:21, supplyVelocity:7, concentration:28, audienceFit:91, novelty:84, sourceStrength:87, informationLeadHours:34, longevity:79, risk:18 },
  { id:'bitcoin-liquidity', topic:'Bitcoin e a nova fase de liquidez global', angle:'Separar narrativa de preço de mudanças macroeconômicas que podem sustentar interesse por várias semanas.', category:'economia', regime:'ACCELERATION', demand:74, demandVelocity:19, demandAcceleration:9, supply:48, supplyVelocity:13, concentration:52, audienceFit:88, novelty:72, sourceStrength:78, informationLeadHours:18, longevity:71, risk:27 },
  { id:'ai-bubble', topic:'A bolha de infraestrutura de IA', angle:'Investigar onde existe investimento produtivo e onde existe excesso de capital antes de a narrativa virar consenso.', category:'economia', regime:'PRE_TREND', demand:46, demandVelocity:13, demandAcceleration:15, supply:19, supplyVelocity:4, concentration:31, audienceFit:86, novelty:90, sourceStrength:82, informationLeadHours:41, longevity:88, risk:24 },
  { id:'space-europa', topic:'A próxima geração de missões às luas oceânicas', angle:'Por que Europa e Encélado voltaram a concentrar atenção científica e quais resultados podem criar novas ondas de interesse.', category:'ciência', regime:'EVERGREEN', demand:38, demandVelocity:5, demandAcceleration:3, supply:24, supplyVelocity:2, concentration:35, audienceFit:83, novelty:76, sourceStrength:89, informationLeadHours:90, longevity:96, risk:8 },
  { id:'social-migration', topic:'A migração de tendências entre TikTok, X e YouTube', angle:'Mostrar como memes e narrativas atravessam plataformas e por que criadores brasileiros normalmente chegam atrasados.', category:'internet', regime:'ACCELERATION', demand:63, demandVelocity:17, demandAcceleration:10, supply:38, supplyVelocity:11, concentration:41, audienceFit:93, novelty:91, sourceStrength:74, informationLeadHours:27, longevity:66, risk:12 },
  { id:'consumer-ai', topic:'Novos dispositivos pessoais com IA', angle:'Comparar a promessa de substituir apps com o que usuários realmente adotam.', category:'tecnologia', regime:'PEAK', demand:94, demandVelocity:7, demandAcceleration:-5, supply:86, supplyVelocity:22, concentration:69, audienceFit:80, novelty:46, sourceStrength:91, informationLeadHours:-9, longevity:48, risk:22 },
  { id:'viral-celebrity', topic:'Polêmica viral de celebridade', angle:'Cobertura do evento já amplamente explorado.', category:'cultura', regime:'DECLINE', demand:43, demandVelocity:-18, demandAcceleration:-12, supply:92, supplyVelocity:9, concentration:77, audienceFit:31, novelty:19, sourceStrength:58, informationLeadHours:-41, longevity:11, risk:43 }
];
